### PR TITLE
Bugfix/san akel/regr include mom rst

### PR DESCRIPTION
**Pull request by sanAkel**
Fixes `item 2` of:
https://github.com/GEOS-ESM/GEOSgcm_App/issues/205
By adding `MOM.res.nc` to the list of restarts that are checked in regression testing.

@sdrabenh: please note this branch is based off `feature/wjiang/mom_dso`(https://github.com/GEOS-ESM/GEOSgcm_App/tree/feature/wjiang/mom_dso) which fixes `item 1`(https://github.com/GEOS-ESM/GEOSgcm_App/issues/205): `LD_PRELOAD`. That's the reason for this **contingency** 🧬

### CODE REVIEW

**Review by yvikhlya — COMMENTED** [review]
The code related to MOM6 restarts should have `>>>MOM6<<<` prefix, e.g.
```
>>>MOM6<<</bin/mv RESTART/MOM.res.nc MOM.res.nc.1
```
This way it will not clutter AMIP and MOM5 set up.

**Review by yvikhlya — APPROVED** [review]

**Comment by sanAkel** [comment]
taking `DNA` off following https://github.com/GEOS-ESM/GEOSgcm_App/pull/204

**Comment by mathomp4** [comment]
@sanAkel This is 0-diff (for AMIP) right? There's no 0-diff or non-zero-diff label.

**Comment by sanAkel** [comment]
> @sanAkel This is 0-diff (for AMIP) right? There's no 0-diff or non-zero-diff label.

@mathomp4 this has no bearing whatsoever on AMIP! Please see `MOM6` protections!

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
