### PR TITLE
Fixes for IOSERVER on Rome

### PR DESCRIPTION
**Pull request by mathomp4**
We know on the Romes that using the MAPL IOSERVER "out of the box" doesn't quite work well. Probably has to do with the number of cores on the Rome being stupid high and...doing things wrong? Dunno.

But, working with @weiyuan-jiang, it was found that the Romes work better if we use the MultiGroup server version of IOSERVER. So this PR tries to "automate" what @weiyuan-jiang said is the best way to set up the MultiGroup server. To wit, he says the best number of backend PEs is the number of history collections divided by the number of ioserver nodes.

This change tries to do that. First, using some `sed` we try to calculate the number of history collections active. I tried my best but I'm guessing somewhere out there is a HISTORY.rc that will break this, but it works with the `HISTORY.AGCM.rc.tmpl` so that's something. 

Once we get that number, we then remove one from it (for the `::` line), and then divide by the number of ionodes. I try to do some ugly `bc` and `awk` to "round up".

Note, it's possible eventually we'd want GEOS to *always* use the MultiGroup server? I'll leave that determination to @bena-nasa, @aoloso, @tclune, and @weiyuan-jiang. Good thing is, we have the code here for it, and we can just make it "everywhere" instead of "just Rome".

### CODE REVIEW

**Review by weiyuan-jiang — COMMENTED** [review]
Maybe we need to add another step to figure out the best $IOS_NODES?

**Review by weiyuan-jiang — COMMENTED** [review]
If there are many npes_model but not enough $IOS_NODES, the performance would degrade

**Comment by mathomp4** [comment]
@weiyuan-jiang I guess at some point it's up to the user. I think @bena-nasa and myself just sort of "guessed" at a good number of IOS_NODES for each resolution given the default layout we set here.

I suppose if a user wants to use more nodes for the model, they should also think about how many IO nodes, etc. 🤷🏼‍♂️

**Comment by mathomp4** [comment]
Tested on discover and it seems to be happy there. I know it also works on the Romes at NAS.

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
