### PR TITLE
Disable Catchment-CN4.5 land model option (LSM_CHOICE=3) for GCM simulations

### PR DESCRIPTION
**Pull request by gmao-jkolassa**
This PR disables the option for using the Catchment-CN4.5 land model (LSM_CHOICE=3) in GCM simulations. The PR also fixes a minor typo that was present in the error message displayed for invalid values of LSM_CHOICE.

This PR is zero-diff.

Related PRs:
https://github.com/GEOS-ESM/GEOSldas/pull/707
https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/900

cc: @gmao-rreichle , @biljanaorescanin

### CODE REVIEW

**Comment by mathomp4** [comment]
Note to @sshakoor1: this will probably need to be done in #544 as well. Though I suppose once this gets in, git would merge the change...

**Review by gmao-rreichle — APPROVED** [review]
Thanks, Jana.  Looks good to me.  Has someone tried running gcm_setup after these mods?  Just to make sure there's not an accidental syntax error in the revisions.

**Comment by gmao-jkolassa** [comment]
`Has someone tried running gcm_setup after these mods? `

Yes, I ran gcm_setup with these modifications trying both LSM_CHOICE=2 and LSM_CHOICE=3 (which is no longer a valid choice). The only options for LSM_CHOICE that are displayed in the interactive script are 1 (Catchment) and 2 (Catchment-CN4.0). And trying to set LSM_CHOICE=3 (Catchment-CN4.5), triggers the error message (which is how I noticed the typo in the error message)

**Comment by gmao-rreichle** [comment]
> Yes, I ran gcm_setup with these modifications t

Thanks, @gmao-jkolassa.    I'm marking this as "ready for review", @sdrabenh.  Please let us know if you have any questions.

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
