### PR TITLE
Feature/acollow/m21caerosolhistory

### PR DESCRIPTION
**Pull request by acollow**
This PR modifies the aerosol output file collections to be used for MERRA-21C.

### CODE REVIEW

**Comment by mathomp4** [comment]
@acollow Do you mean for this to go into `R21C`? Your edits seem to be behind `develop` in many files.

**Comment by acollow** [comment]
Yeah, this is more so relevant for R21C. I will eventually be making the same changes to ALL of the HISTORY.rc templates. I realized by base is a bit out dated but unfortunately I am very tied up this week. I have about an hour I can spend on updating this tomorrow morning.

**Comment by elakkraoui** [comment]
> @acollow Do you mean for this to go into `R21C`? Your edits seem to be behind `develop` in many files.

@mathomp4, please hold off on this. We shouldn't be changing files beyond the R21C project. 

@acollow, you need to separate your PRs. Some of your changes are targeting FP. The **only** file you can submit a PR for in R21C is HISTORY_R21C.tmpl.  

Also, the updated solar file is v23 not v21, and the  USE_EXTDATA2G is already true by default in R21C.  

We need to talk before you submit your PR.

**Comment by elakkraoui** [comment]
> Yeah, this is more so relevant for R21C. I will eventually be making the same changes to ALL of the HISTORY.rc templates. I realized by base is a bit out dated but unfortunately I am very tied up this week. I have about an hour I can spend on updating this tomorrow morning.

@acollow, the only file that is relevant to M21C is HISTORY_R21C.tmpl! please separate your PRs.

**Comment by acollow** [comment]
@elakkraoui, I only changed HISTORY_R21C.rc.tmpl. The other files that changed were because I pushed it from a past out of the box build that I had used for a DAS run and arise as "conflicts" because of changes that happened in the tag since then. I haven't updated the other HISTORY files yet, nor did I touch CAP.rc.tmpl. Tomorrow morning I can update this, likely by closing this PR  and opening is new one that is actually based on the R21C tag.

**Comment by elakkraoui** [comment]
> @elakkraoui, I only changed HISTORY_R21C.rc.tmpl. The other files that changed were because I pushed it from a past out of the box build that I had used for a DAS run and arise as "conflicts" because of changes that happened in the tag since then. I haven't updated the other HISTORY files yet, nor did I touch CAP.rc.tmpl. Tomorrow morning I can update this, likely by closing this PR and opening is new one that is actually based on the R21C tag.

@acollow, Ok I see.

**Pull request closed without merging**
