### PR TITLE
Updates history templates to use GOCART2G convective scavenging field

### PR DESCRIPTION
**Pull request by acollow**
Solves issue #335

### CODE REVIEW

**Comment by sdrabenh** [comment]
@pcolarco I added your recommendations from your history file to this @acollow pull request via the commit above: https://github.com/GEOS-ESM/GEOSgcm_App/pull/336/commits/eebc66a72bbce53cea2ab9d75270597bb5a057f8
Would you both please take a look at these changes and determine if this would be the desired default for these collections, or whether further changes should be made? If everything looks okay, I can try to replicate these changes to `HISTORY.rc.tmpl`. Question: would there ever be changes to the number of bins and how would that effect aliases like this 'DUEM001;DUEM002;DUEM003;DUEM004;DUEM005'? Or would we be better off without explicit aliases?

**Comment by pcolarco** [comment]
@sdrabenh I’ll have a look later today. To your last question: hard wire the suggested aliases. There’s no plan to change the number of bins. A user *can* make that change, but they need to know what they’re doing anyway (new optics tables, etc.) so it’d be on them.

**Comment by mathomp4** [comment]
Note. We will need to be careful once #317 is brought in. If this PR beats #317, then we'll probably want @pcolarco or @acollow to make sure we merge/conflict resolve the name change by @amdasilva and @weiyuan-jiang correctly. Shouldn't be hard, just need to be careful.

**Review by pcolarco — COMMENTED** [review]
@sdrabenh Line 1004 change alias to "BRCEXTCOEF". The misspelling is somehow in my own HISTORY, sorry.

I don't see the scavenging diagnostics discussed the other day in the tavg2d_aer_x template.

**Comment by acollow** [comment]
@pcolarco, the scavenging diagnostics are in the first commit at https://github.com/GEOS-ESM/GEOSgcm_App/pull/336/commits/440bbc002ddf81bf6337367842f7acb712f47cbd

**Comment by sdrabenh** [comment]
> @sdrabenh Line 1004 change alias to "BRCEXTCOEF". The misspelling is somehow in my own HISTORY, sorry.

Fixed.

> I don't see the scavenging diagnostics discussed the other day in the tavg2d_aer_x template.

Sorry, that link was for my changes only based on your history. It is best to click on the "Files changed" tab at the top to see the full changes this PR does - including the diagnostics.

**Comment by sdrabenh** [comment]
> Note. We will need to be careful once #317 is brought in. If this PR beats #317, then we'll probably want @pcolarco or @acollow to make sure we merge/conflict resolve the name change by @amdasilva and @weiyuan-jiang correctly. Shouldn't be hard, just need to be careful.

@mathomp4 is correct. We will have to be careful merging and resolving conflicts. This PR will go in first because these changes are valid right now. I will have to update #317 accordingly for the upcoming x-experiment and eventually once @amdasilva tags the changes currently in GOCART/develop

**Comment by pcolarco** [comment]
@sdrabenh Looking back over the changed files it is not obvious to me that this is right. HISTORY.AGCM.rc.tmpl looks okay, but the later templates are inconsistent in the naming of the brown carbon variables and appear incorrect in terms of some of the scavenging diagnostics. E.g., HISTORY.rc.tmpl line 1420 -- s/b BRC and not BR. Line 1477 and 1481 also look wrong. Didn't look at later ones. However, except for HISTORY.AGCM.rc.tmpl where you seem to have taken my changes there is a consistent tendency to call the Brown Carbon "BR" when I have always used "BRC". My preference there breaks the neat two letter symmetry and what was implemented for the internal state (which calls it "br"), so I'm prepared to be told I'm wrong and it needs to be changed, but someone needs to decide what the final form should be and it should be consistent in *all* the templates. Does @amdasilva need to decide that?

**Comment by sdrabenh** [comment]
> @sdrabenh Looking back over the changed files it is not obvious to me that this is right. HISTORY.AGCM.rc.tmpl looks okay, but the later templates are inconsistent in the naming of the brown carbon variables and appear incorrect in terms of some of the scavenging diagnostics. E.g., HISTORY.rc.tmpl line 1420 -- s/b BRC and not BR. Line 1477 and 1481 also look wrong. Didn't look at later ones. 

These latest changes were only done to `HISTORY.AGCM.rc.tmpl` with the intention to replicate the changes the other templates. I was waiting the green light first.

> However, except for HISTORY.AGCM.rc.tmpl where you seem to have taken my changes there is a consistent tendency to call the Brown Carbon "BR" when I have always used "BRC". My preference there breaks the neat two letter symmetry and what was implemented for the internal state (which calls it "br"), so I'm prepared to be told I'm wrong and it needs to be changed, but someone needs to decide what the final form should be and it should be consistent in _all_ the templates. Does @amdasilva need to decide that?

My inclination would be to revert back to the neat 2-letter BR because 1) this was the original G2G history changes provided by @amdasilva, 2) this is consistent with the component name CA.br, 3) we were already using this in existing experiments, and 4) the plots package and experiment webpage key-off BR now. Unless there is a strong objection, I would prefer to use BR instead of BRC aliases.

**Comment by pcolarco** [comment]
@sdrabenh I can live with that if that was @amdasilva's preference.

**Comment by sdrabenh** [comment]
@pcolarco @acollow I edited `HISTORY.rc.tmpl` the best I could. However, there seemed to be many inconsistencies therein, and someone from the aerosol group should go through this with a fine-tooth comb. If you would be able to look specifically at `HISTORY.rc.tmpl` to see if anything is missing, incorrect, or should be rearranged, please let me know. As a starting point, I still have a number of questions:

1. I don't fully understand the purpose of extended collections: `tavg3_2d_aer_Nx` vs. `tavg3_2d_adg_Nx` and `tavg3_3d_aer_Np` vs. `tavg3_3d_ext_Np` and what should be in each. 
2. There are still multiple aliases to things - for example:
```
1302:                               'CASVCA.br'        , 'CA.br'      , 'BRSV001;BRSV002' ,
1438:                               'DBRC2gDT'         , 'MOIST'      ,  'BRSV'    ,
```
3. Without digging through the code, I'm unsure to what extend 2d fields should also be in 3d collections.
4. What does the `*.conservative: 1` option specify? Should this be in all 4 collections?

**Comment by acollow** [comment]
This was (or at least should be) one of the lines that I removed to clean things up. Scavenging within the carbon gridcomp is defunct. If @pcolarco  and @amdasilva agree, I am in favor of completely removing it from all HISTORY templates for the time being, as opposed to commenting them out until if/when scavenging moves back into GOCART.

1302:                               'CASVCA.br'        , 'CA.br'      , 'BRSV001;BRSV002' ,

**Comment by acollow** [comment]
I also don't understand why the block below is included in the tavg2d_aer_x collection. This should only be in the adg collection. 

                               'DUEM'        , 'DU'      , 'DUEM001;DUEM002;DUEM003;DUEM004;DUEM005' ,
                               'DUSD'        , 'DU'      , 'DUSD001;DUSD002;DUSD003;DUSD004;DUSD005' ,
                               'DUDP'        , 'DU'      , 'DUDP001;DUDP002;DUDP003;DUDP004;DUDP005' ,
                               'DUWT'        , 'DU'      , 'DUWT001;DUWT002;DUWT003;DUWT004;DUWT005' ,

**Comment by pcolarco** [comment]
@acollow Yes, the line 1302 referenced above should go away. Similar lines in any other templates too. Scavenging diagnostics only come from MOIST now.

**Comment by bena-nasa** [comment]
> @sdrabenh I am not sure I'm the arbiter of what the HISTORY templates _should_ be. Primarily I work on the HISTORY.AGCM.rc.tmpl, and so I have a different idea of what the collections should be for research runs than what is in FP. The splitting up into the extended collections was imposed from on high and I was never clear on the rationale or how the split decisions were made.
> 
> The "conservative" tag is to ensure an area weighted remapping is imposed on the output fields. This is important especially for the tavg2d_aer/adg_x collection to ensure we can close the budget on the aerosol emission and loss terms. My preference is it is on for all the aerosol collections, but I don't know if there's a good reason not too (faster output?)

There should be no appreciable difference in speed, the transforms are generated once and is fast, the application of the transform is very fast. Speed should be the last thing one worries about when choosing a regridding method. Choose what is appropriate scientifically.

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
