### PR TITLE
Major fixes to enable EASY coupled model experiments

### PR DESCRIPTION
**Pull request by sanAkel**
The intent of this PR is to make our life simple(r) in setting up GEOS coupled model experiments for all of these [resolution combinations](https://github.com/GEOS-ESM/GEOSgcm/wiki/Coupled-model-configurations-(GEOS-MOM6)).

**Proposed changes**:

1. The default ocean model for `gcm_setup` is MOM6. ✅ @sanAkel 
2. Use the BCs shared path on discover: `/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/ocean/MOM6/` to pick up files needed by MOM6 ✅ @sanAkel 
3. **To do** ❎ @mathomp4 **Layout needs to be made consistent.**
4. **To do** ❎ @mathomp4 [Options needed to be locked up with the atmosphere as in this table](https://github.com/GEOS-ESM/GEOSgcm/wiki/Coupled-model-configurations-(GEOS-MOM6)).

### Layout:

AGCM.rc `NX x NY` should match MOM’s `LAYOUT` listed in `MOM_override` see [this table](https://github.com/GEOS-ESM/GEOSgcm/wiki/Coupled-model-configurations-(GEOS-MOM6)) or ⬇️ .

AGCM `NX x NY` and OGCM `NX x NY` need to be _fixed_ in `AGCM.rc` in the following manner:

|  Configuration Name | AGCM (NX x NY) | OGCM (NX x NY) |  [Layout in MOM_override](https://github.com/GEOS-ESM/GEOS_OceanGridComp/tree/develop/MOM6_GEOSPlug/mom6_app) | 
| :--           | :--: | :--: | --: |
| Low         | 1 x 6  | 3 x 2 |  3 x 2 |
| Medium  | 5 x 36  | 90 x 2 | 90 x 2 |
| High       |  30 x 36 | 36 x 30 | 36 x 30 |

### Options:

See following example for setting up [_high_ resolution experiment](https://github.com/GEOS-ESM/GEOSgcm/wiki/Coupled-model-configurations-(GEOS-MOM6)):

```
discover13.sakella 1046> gcm_setup

Enter the Experiment ID:
testH
Enter a 1-line Experiment Description:
test
Do you wish to CLONE an old experiment? (Default: NO or FALSE)

Enter the Atmospheric Horizontal Resolution code:
--------------------------------------
            Cubed-Sphere
--------------------------------------
   c12  -- 8    deg (750.0    km) 
   c24  -- 4    deg (375.0    km) 
   c48  -- 2    deg (187.5    km) 
   c90  -- 1    deg (100.0    km) 
   c180 -- 1/2  deg ( 50.0    km) 
   c360 -- 1/4  deg ( 25.0    km)  
   c720 -- 1/8  deg ( 12.5    km) 
   c1440 - 1/16 deg (  6.25   km) 
   c2880 - 1/32 deg (  3.125  km) 
   c5760 - 1/64 deg (  1.5625 km) 
            CONUS Stretched Grids                
   c270 -- ( 16.0 -100 km)  
   c540 -- (  8.0 - 50 km)  
   c1080 - (  4.0 - 25 km)  
   c1536 - (  2.0 - 20 km)  
   c2160 - (  2.0 - 12 km)  
 
c180
Enter the Atmospheric Model Vertical Resolution: LM (Default: 72)

Enter Choice for Atmospheric Model Microphysics: (Default: BACM_1M)
   BACM_1M  --  3-phase 1-moment Bacmeister et al
   GFDL_1M  --  6-phase 1-moment Geophysical Fluid Dynamics Laboratory
   MGB2_2M  --  5 or 6-phase 2-moment Morrison & Gettleman

Use Hydrostatic Atmosphere? (Default: TRUE)

Do you wish to IOSERVER? (Default: YES or TRUE)

Enter the Processor Type you wish to run on:
   mil  (Milan) (default)
 

Do you wish to run the COUPLED Ocean/Sea-Ice Model? (Default: NO or FALSE)
YES

Choose an Ocean Model: (Default: MOM6)
   MOM5
   MOM6
   MIT

Choose a Seaice Model: (Default: CICE4)
   CICE4
   CICE6

Enter the Ocean Lat/Lon Horizontal Resolution: IM JM (Default: 360 210)
1440 1080
Enter the Ocean Model Vertical Resolution: LM (Default: 50)
75
Enter the choice of  Land Surface Boundary Conditions using: 1 (Icarus), 2 (Default: Icarus-NLv3)
...
...
```

**The user does not need to answer**: `Enter the Ocean Lat/Lon Horizontal Resolution: IM JM (Default: 360 210)`: 1440 1080 **and** `Enter the Ocean Model Vertical Resolution: LM (Default: 50)`: 75. Since a choice was made to run:
- With C180 atmospheric resolution
- And Coupled.

This [table](https://github.com/GEOS-ESM/GEOSgcm/wiki/Coupled-model-configurations-(GEOS-MOM6)) provides only one option for ⬆️ choices, hence that should be automatically populated. **It can simply echo that it has been filled in.**

Similarly for C90 and C12.

### CODE REVIEW

**Review by yvikhlya — APPROVED** [review]

**Comment by sanAkel** [comment]
⬆️ Items 3 and 4 will be addressed via https://github.com/GEOS-ESM/GEOSgcm_App/pull/542#pullrequestreview-1744582456

**Comment by sanAkel** [comment]
We need [this PR](https://github.com/GEOS-ESM/GEOS_OceanGridComp/pull/54) to be merged as well for all the `High` configuration to be set up automatically.

**Comment by mathomp4** [comment]
I've merged in #542 into here. Something is missing and I'm not sure what. But maybe I didn't branch right...

**Comment by sanAkel** [comment]
> I've merged in #542 into here. Something is missing and I'm not sure what. But maybe I didn't branch right...

@mathomp4 Is it something I can help with?

**Comment by mathomp4** [comment]
> > I've merged in #542 into here. Something is missing and I'm not sure what. But maybe I didn't branch right...
> 
> @mathomp4 Is it something I can help with?

CI failed to run in my branch. Not sure why. So I merged mine over here to see if maybe I was missing something. If that fails, I'll get on to the cloud instance and see what I see...

**Comment by mathomp4** [comment]
Yay! 🎉

**Comment by sanAkel** [comment]
Fantastic! :)

**Review by sdrabenh — APPROVED** [review]
Works for me as discussed herein

**Pull request merged**
