### PR TITLE
Sync up changes from 537 into other setups

### PR DESCRIPTION
**Pull request by mathomp4**
This PR pulls in the changes to DT made in #537 into the other setup scripts.

Not sure how to label this. I mean, it's zero-diff in the sense that the model didn't change, but non-zero-diff in that if you run these resolutions, answers will change.

CC: @mmanyin

### CODE REVIEW

**Review by mmanyin — APPROVED** [review]
Yes, the timesteps should mirror GCM, except in GMI where SOLAR and IRRAD should have the same DT as GMI.  All looks OK to me.

**Comment by mmanyin** [comment]
Actually, for GMI, please change DT for GMI, SOLAR, IRRAD and OCEAN   in the BACM clause.  They all hinge on DT, so overriding DT should override their values as well.

**Comment by mathomp4** [comment]
> Actually, for GMI, please change DT for GMI, SOLAR, IRRAD and OCEAN in the BACM clause. They all hinge on DT, so overriding DT should override their values as well.

Okay. A little help here. Do you mean that this:
```
# Per W. Putman recommendation, set heartbeat to 450s anytime BACM_1M is selected
if( "$CLDMICRO" == "BACM_1M" ) then
   set DT = 450
   set LONG_DT = 450
endif
```
should be:
```
# Per W. Putman recommendation, set heartbeat to 450s anytime BACM_1M is selected
if( "$CLDMICRO" == "BACM_1M" ) then
   set DT = 450
   set LONG_DT = 450
   set SOLAR_DT  = `expr $DT \* 2`
   set IRRAD_DT  = `expr $DT \* 2`
   set OCEAN_DT = $IRRAD_DT
endif
```
in `gmichem_setup`?

**Comment by mmanyin** [comment]
Yes, and please add GMICHEM_DT  defined the same as SOLAR and IR

**Comment by mathomp4** [comment]
> Yes, and please add GMICHEM_DT defined the same as SOLAR and IR

Okay. I think I did that. Take a look

**Comment by mmanyin** [comment]
> Okay. I think I did that. Take a look

That's it, thanks!

**Review by mmanyin — APPROVED** [review]
these look good

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
