### PR TITLE
Add LD_PRELOAD for Coupled Model

### PR DESCRIPTION
**Pull request by mathomp4**
Recent testing with mom5 by @yvikhlya and @sanAkel (see https://github.com/GEOS-ESM/GEOSgcm/issues/352 and https://github.com/GEOS-ESM/GEOSgcm/issues/430) in GEOSgcm has shown a need to bring back the old `LD_PRELOAD` mechanism that was removed in #204. So this PR brings back `LD_PRELOAD` but only in the case of MOM5

Obviously not ideal, but until this oddity can be examined by @tclune and @weiyuan-jiang (and maybe @atrayano), ~we bring back `LD_PRELOAD` *ONLY* when running MOM5 as runs of MOM6 don't seem to care!~

As @yvikhlya pointed out below, MOM6 might only work due to luck. So we preload both.

### CODE REVIEW

**Comment by yvikhlya** [comment]
@mathomp4 I thinks both MOM5 and MOM6 need explicit LD_PRELOAD. MOM6 does not care now because it luckily goes first in load list (check `ldd GEOSgcm.x`), but if somebody will change something in cmake for example which will cause libmom6.so to go behind libmom5.so, we will scratch our heads again, why MOM6 does not work

**Comment by mathomp4** [comment]
> @mathomp4 I thinks both MOM5 and MOM6 need explicit LD_PRELOAD. MOM6 does not care now because it luckily goes first in load list (check `ldd GEOSgcm.x`), but if somebody will change something in cmake for example which will cause libmom6.so to go behind libmom5.so, we will scratch our heads again, why MOM6 does not work

Hmm. Well, I can add that if you like. Give me a second...

**Comment by mathomp4** [comment]
@yvikhlya Okay, this should now preload both.

**Review by yvikhlya — APPROVED** [review]

**Comment by mathomp4** [comment]
Note: I probably need to generalize this for macOS since it is `libmom6.dylib` on that. I'll need to figure the best way to do this.

**Comment by mathomp4** [comment]
I've pushed my generalized updates. Honestly, I think LD_PRELOAD might be ignored on macOS, not sure as it seemed to work with *both* `.so` and `.dylib` and the first obviously doesn't exist. But, well, I figure we should at least make it look right on macOS. 😄

**Review by sanAkel — APPROVED** [review]
Seems to work for MOM6. 

I have no working restarts at `1-deg` for MOM5, but by the history of this issue and given the lines of changes, I am _confident_ that it will work for MOM5 as well.

For the record, this PR 
fixes: https://github.com/GEOS-ESM/GEOSgcm/issues/430
and
resolves: https://github.com/GEOS-ESM/GEOSgcm/issues/352

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
