### PR TITLE
Fixes #147. Add logging capability

### LINKED ISSUE #147: Provide a default logging.yaml file
Thus far we have allowed a simple set of defaults for pflogger and have required users to manually create a ```logging.yaml``` file to customize.  Further, they have to modify ```gcm_run.j``` to copy the config file into the scratch directory for the run.

Now it is time to include a default `logging.yaml` file in the GCM app and modify the setup script to automatically use that file by default.    I will follow up shortly with a sensible initial file, but I will expect it will change quickly as we do further deployment.

### PR DESCRIPTION
**Pull request by mathomp4**
This PR closes #147 in providing logging capability the GCM.

### CODE REVIEW

**Comment by tclune** [comment]
I found a more complete list of the loggers we want:
```
# GCM.DATATM:
# GCM.AGCM:
# GCM.AGCM.SCMDYNAMICS:
# GCM.AGCM.SCMDYNAMICS.DYN:
# GCM.AGCM.SCMDYNAMICS.ADV:
# GCM.AGCM.SUPERDYNAMICS:
# GCM.AGCM.SUPERDYNAMICS.DYN:
# GCM.AGCM.SUPERDYNAMICS.ADV:
# GCM.AGCM.PHYSICS:
# GCM.AGCM.PHYSICS.GWD:
# GCM.AGCM.PHYSICS.MOIST:
# GCM.AGCM.PHYSICS.TURBULENCE:
# GCM.AGCM.PHYSICS.CHEMISTRY:
# GCM.AGCM.PHYSICS.CHEMISTRY.HEMCO:
# GCM.AGCM.PHYSICS.CHEMISTRY.PCHEM:
# GCM.AGCM.PHYSICS.CHEMISTRY.ACHEM:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.BC:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.BRC:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.CFC:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.CH4:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.CO2:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.CO:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.DU:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.NI:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.O3:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.OC:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.Rn:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.SS:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.SU:
# GCM.AGCM.PHYSICS.CHEMISTRY.GOCART.data:
# GCM.AGCM.PHYSICS.CHEMISTRY.GAAS:
# GCM.AGCM.PHYSICS.CHEMISTRY.H2O:
# GCM.AGCM.PHYSICS.CHEMISTRY.STRATCHEM:
# GCM.AGCM.PHYSICS.CHEMISTRY.GMICHEM:
# GCM.AGCM.PHYSICS.CHEMISTRY.CARMA:
# GCM.AGCM.PHYSICS.CHEMISTRY.GEOSCHEMCHEM:
# GCM.AGCM.PHYSICS.CHEMISTRY.MATRIX:
# GCM.AGCM.PHYSICS.CHEMISTRY.MAM:
# GCM.AGCM.PHYSICS.CHEMISTRY.TR:
# GCM.AGCM.PHYSICS.CHEMISTRY.DNA:
# GCM.AGCM.PHYSICS.SURFACE:
# GCM.AGCM.PHYSICS.SURFACE.SALTWATER:
# GCM.AGCM.PHYSICS.SURFACE.LAKE:
# GCM.AGCM.PHYSICS.SURFACE.LANDICE:
# GCM.AGCM.PHYSICS.SURFACE.LAND:
# GCM.AGCM.PHYSICS.SURFACE.LAND.VEGDYN:
# GCM.AGCM.PHYSICS.SURFACE.LAND.<CATCH>:
# GCM.AGCM.PHYSICS.SURFACE.LAND.<CATCHCN>:
# GCM.AGCM.PHYSICS.SURFACE.LAND.<ens>:
# GCM.AGCM.PHYSICS.RADIATION:
# GCM.AGCM.PHYSICS.RADIATION.SOLAR:
# GCM.AGCM.PHYSICS.RADIATION.IRRAD:
# GCM.AGCM.PHYSICS.RADIATION.SATSIM:
# GCM.AGCM.ORBIT:
# GCM.AIAU:    
# GCM.OGCM:
# GCM.OGCM.OBIO:
# GCM.OGCM.ORAD:
# GCM.OGCM.SEAICE:
# GCM.OGCM.SEAICEdata:
# GCM.OGCM.OCEAN:
# GCM.OGCM.OCEAN.DATASEA:
# GCM.OGCM.OCEAN.MOM:
# GCM.OGCM.OCEAN.MOM6:
```

**Comment by tclune** [comment]
The consoled handler should be default ```INFO``` instead of ```WARNING```

**Comment by mathomp4** [comment]
@tclune I'll add your new list. Should I add `CAP.` before them?

**Comment by tclune** [comment]
Yes - thank you.

**Pull request merged**
