### PR TITLE
Setup Fixes for GOCART2G Data Driven

### PR DESCRIPTION
**Pull request by mathomp4**
Thanks to the work of @pcolarco in https://github.com/GEOS-ESM/GOCART/pull/211 running GOCART2G Data is possible again!

This PR will track changes necessary to have `gcm_setup` et al set things up automatically for users for a data driven experiment.

I freely admit it is quite ugly at the moment and I know @pcolarco might be planning further changes to the Chem Grid Comp as well. But, what is here works for now.

Also, I'll need to consult with @mmanyin and @christophkeller on getting the gmi, strat, and geoschem setup scripts to have the same fixes. But that can be done once we are happy with `gcm_setup`.

### CODE REVIEW

**Comment by mathomp4** [comment]
Note: As @wmputman would like this in testing, I'm going to un-WIP this and undraft. Note that I have *NOT* pulled these changes into the GMI, SC or GCC setup scripts.

I think `geoschemchem_setup` would be pretty simple, but `gmichem_setup` and `stratchem_setup` are just too ... different when it comes to chemistry selection (obviously), that I don't want to screw it up.

Once @pcolarco finalizes everything and this is more "official" I can work with @mmanyin on getting to work with the other chemistries.

**Comment by mmanyin** [comment]
> Note: As @wmputman would like this in testing, I'm going to un-WIP this and undraft. Note that I have _NOT_ pulled these changes into the GMI, SC or GCC setup scripts.
> 
> I think `geoschemchem_setup` would be pretty simple, but `gmichem_setup` and `stratchem_setup` are just too ... different when it comes to chemistry selection (obviously), that I don't want to screw it up.
> 
> Once @pcolarco finalizes everything and this is more "official" I can work with @mmanyin on getting to work with the other chemistries.

Agreed!

**Comment by pcolarco** [comment]
I did not look at this again yet. Are we looking for removal of the “GOCART_DATA” functionality entirely?


--------------------------------------------------------------------
Peter Colarco
NASA GSFC
Code 614
NASA Goddard Space Flight Center
Greenbelt, MD 20771
301.614.6382 (ph)
301.614.5903 (fax)

***@***.******@***.***>
http://acd-ext.gsfc.nasa.gov/People/Colarco
http://www.researcherid.com/rid/D-8637-2012
--------------------------------------------------------------------


From: Mike Manyin ***@***.***>
Reply-To: GEOS-ESM/GEOSgcm_App ***@***.***>
Date: Monday, March 27, 2023 at 11:50 AM
To: GEOS-ESM/GEOSgcm_App ***@***.***>
Cc: Peter Colarco ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSgcm_App] Setup Fixes for GOCART2G Data Driven (PR #419)


Note: As @wmputman<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwmputman&data=05%7C01%7Cpeter.r.colarco%40nasa.gov%7C347a4a25f2704fb6680108db2edaf195%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638155290116603276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Gy2lXMSkEuTFMuzYz%2BOd3CxlRKa9UgUlTB0Cz2feEic%3D&reserved=0> would like this in testing, I'm going to un-WIP this and undraft. Note that I have NOT pulled these changes into the GMI, SC or GCC setup scripts.

I think geoschemchem_setup would be pretty simple, but gmichem_setup and stratchem_setup are just too ... different when it comes to chemistry selection (obviously), that I don't want to screw it up.

Once @pcolarco<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpcolarco&data=05%7C01%7Cpeter.r.colarco%40nasa.gov%7C347a4a25f2704fb6680108db2edaf195%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638155290116603276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DZz3ZRCVzMRHBDr8vAaXqOoArXS%2BF1I2LAQt51JOYLU%3D&reserved=0> finalizes everything and this is more "official" I can work with @mmanyin<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmmanyin&data=05%7C01%7Cpeter.r.colarco%40nasa.gov%7C347a4a25f2704fb6680108db2edaf195%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638155290116603276%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=owBtF4Ba8gHgM4cCB6nqw25cknXsx58TNa3AsAZ97Cs%3D&reserved=0> on getting to work with the other chemistries.

Agreed!

**Comment by sdrabenh** [comment]
Removed 0-diff label because of [Donifan's 1MOM bug fixes for seasalt](https://github.com/GEOS-ESM/GOCART/commit/f4c7da3a2b1cedced27011dd66a7ef854c674630) in GOCART

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
